### ISSUE TITLE
画像生成用ライブラリを最新バージョンに更新する

### ISSUE THREAD

**Issue by ics-matsumoto** [ics-creative/160609_animation-image-generator#11]
画像生成に使用しているライブラリ（バイナリモジュール）の更新要否を調査・対応する

## 対象
- product/resources/
  - apngasm-2.9.1-bin-macos / apngasm-2.9.1-bin-win32
  - libwebp-1.0.0-mac-10.13 / libwebp-1.0.0-windows-x86
  - pngquant-mac / pngquant-win （※ ver 2.7.1）

## 方針
- 大きな非互換がなく差し替え可能なら更新する
- 対象のOS,アーキテクチャを確認する
  - MacはARM対応の有無を確認する
  - このタスクではARMへの切り替えは必須ではない（別途チケット化する）

**Comment by ics-matsumoto** [comment]
## apngasm

SourceForgeで配布されているバイナリ版は2.91以降更新なし
https://sourceforge.net/projects/apngasm/files/

最新版は3.1.10が[github.com/apngasm/apngasm](https://github.com/apngasm/apngasm)で公開されている
AppleSilicon対応。ただし、バイナリはないので自前でビルドが必要
Windows版のビルドにはVisualStudioが必要とのこと

## libwebp

最新版は1.2.2
https://storage.googleapis.com/downloads.webmproject.org/releases/webp/index.html

x86版とarm版それぞれ提供されてるので、そのまま使うのであればビルド時に切り分けるか、Mac向けには両方バンドルして実行時に切り分けるかの対応が必要

## pngquant

最新版は2.17
https://pngquant.org/
バイナリ版はユニバーサルバイナリになってるので、このまま入れ替えればOK

```sh
% file pngquant
pngquant: Mach-O universal binary with 2 architectures: [x86_64:Mach-O 64-bit executable x86_64] [arm64:Mach-O 64-bit executable arm64]
pngquant (for architecture x86_64):	Mach-O 64-bit executable x86_64
pngquant (for architecture arm64):	Mach-O 64-bit executable arm64
```

**Comment by ics-matsumoto** [comment]
上記を踏まえたv2.2リリースでの更新案

## apngasm
- apngasm-2.91-bin-macos （変更なし）
- apngasm-2.91-bin-win32（変更なし）

## libwebp
- libwebp-1.0.0-mac-x86-64 → libwebp-1.2.2-mac-x86-64
- libwebp-1.0.0-windows-**x86** → libwebp-1.2.2-windows-**x64**

## pngquant
- pngquant-mac（ver2.7.1） → pngquant-2.17.0-mac ※ユニバーサルバイナリ
- pngquant-win （ver2.7.1）→ pngquant-2.17.0-win

----
今後AppleSilicon対応する際の対応
electronの更新とは別に画像生成用ライブラリに関して、下記の検討が必要

- apngasmはWindows用の最新バイナリが簡単には手に入らなそうなのでMacのみバージョンを上げるか代替ツールへの切り替えを検討する必要あり
  - Mac版はHomebrewで入るが、多分端末でコンパイルする形。生成されたバイナリを添付して問題ないか（動作・ライセンス的に）要確認
- libwebpにarm版を追加して切り分けを行う。または自前でユニバーサルバイナリを作る

@ics-ikeda @ics-nohara ひとまず当座の対応(v2.2リリース)にいては上記の方針で良いでしょうか？
ひとまずMac版に関しては上記でざっくりと動作することは確認しています。

**Comment by ics-nohara** [comment]
@ics-matsumoto 調査・検討ありがとうございます。方針問題なさそうですので、このまま進めていただけたらと思います。
