### ISSUE TITLE
[連番画像を再選択]ボタンが動作しない

### ISSUE THREAD

**Issue by ics-nohara** [ics-creative/160609_animation-image-generator#17]
### 手順
1. アプリを起動し、任意の画像を選択する
2. [連番画像を再選択]ボタンを押す
3. 任意の画像を選択する
4. コマ画像プレビューに1で選んだ画像がそのまま表示され、[連番画像を再選択]で選んだ画像が表示されない

### 期待する結果
[連番画像を再選択]で選んだ画像がコマ画像プレビューに表示されること

**Comment by ics-matsumoto** [comment]
ngOnInitでサービスのPromise解決を待つ作りになっているのため、2度目以降が発火しないようです。
Promiseではなくイベントハンドラーのような仕組みにすれば解決できそうに思います。

https://github.com/ics-creative/160609_animation-image-generator/blob/5e570e6e7f5ae0e23a4d16af657135524b198b04/product/src/app/components/app/app.ts#L77-L83

**Comment by ics-nohara** [comment]
調査とご対応ありがとうございます。修正PRをマージしたためクローズします。
