### ISSUE TITLE
新しいLINEスタンプの形式に対応する

### ISSUE THREAD

**Issue by ics-matsumoto** [ics-creative/160609_animation-image-generator#28]
通常のアニメーションスタンプ以外のサポートを追加する

- [ポップアップスタンプ](https://creator.line.me/ja/guideline/popupsticker/)
- [エフェクトスタンプ](https://creator.line.me/ja/guideline/effectsticker/)

主な違いはサイズ等のチェックルールのみなので、設定パネル内で使用用途を選択し、用途に合わせたチェックを行うなどのUIを追加を検討する

**Comment by ics-nishihara** [comment]
@ics-matsumoto 

#29 とも関連しますが、各種ラインスタンプ形式を選択できるUIの追加とバリデーションの連携を行いました。
ご確認お願いします。

**Comment by ics-matsumoto** [comment]
v4リリースで対応済みなのでクローズ
