### ISSUE TITLE
エラーチェックUIの強化

### ISSUE THREAD

**Issue by ics-matsumoto** [ics-creative/160609_animation-image-generator#29]
LINEスタンプの形式チェックエラーが保存完了後まで表示されないため、表示を強化する
- 画面上部にラベルの色としてエラーが示されているので、具体的なエラー内容をツールチップや追加のUIによって表示する

ファイルサイズ（ピクセル数）不一致のエラーが読み込み・保存時のダイアログとしてしか表示されないため、表示を強化する
- 画面上部のサイズラベル部分でエラーを示す等、表示方法を改善したい

**Comment by ics-nishihara** [comment]
@ics-matsumoto 
こちらの件ですが、#57 にて

- エラー時のツールチップ表示
- エラー内容をツールチップ内に表示

の実装を行いました。ご確認お願いします。

**Comment by ics-matsumoto** [comment]
こちらもv4で対応済みなのでクローズします
