### ISSUE TITLE
Windowsでのアイコンの表示が小さく、背景が透過していない

### ISSUE THREAD

**Issue by ics-ikeda** [ics-creative/160609_animation-image-generator#73]
アニメ画像に変換する君のWindows版において、アイコンが綺麗に表示されていないようです。
バージョン 4.1 で動作確認しました。

Windows 11 : アイコンが小さい

![image](https://user-images.githubusercontent.com/975273/214514920-a4420460-7281-44a9-bb41-056f81706a3f.png)

Windows 11: タスクバー上のアイコンが透過しているっぽい？

![image](https://user-images.githubusercontent.com/975273/214514940-bfb16449-2cbe-44b7-9ce0-7aad04676d8a.png)

Windows 10 : アイコンが小さい

![image](https://user-images.githubusercontent.com/975273/214514965-9e306fcf-ae70-426d-b4e1-32836c0ef678.png)

Windows 10: タスクバー上のアイコンが透過しているっぽい？

![image](https://user-images.githubusercontent.com/975273/214514990-a6e1bbae-7f69-44ca-9e1f-6810560795c5.png)

■期待値

- プログラムメニューのアイコン： 視認できる大きさで表示されていること
- タスクバーのアイコン： アイコンの●の外側が不自然のない透過背景で表示されていること。周りのアイコンに比べて同じぐらいの●で表示されていること。

**Comment by ics-nohara** [comment]
v4.2でリリース済みのためクローズします。
