### ISSUE TITLE
Windows 11で、表示倍率の文字が少し見切れている

### ISSUE THREAD

**Issue by ics-ikeda** [ics-creative/160609_animation-image-generator#80]
バージョン4.2にて確認しました。

エディション	Windows 11 Pro
バージョン	21H2

<img width="798" alt="image" src="https://user-images.githubusercontent.com/975273/216886317-1fd5e1b6-7dba-4531-ab72-f13616811ea7.png">

**Comment by ics-nohara** [comment]
@ics-ikeda  バージョン5.0でリリースされたため、Closeします。Issue登録ありがとうございました！
