### ISSUE TITLE
容量最適化の「？」の配置が不自然

### ISSUE THREAD

**Issue by ics-ikeda** [ics-creative/160609_animation-image-generator#89]
「容量最適化」の右側の「？」の位置に違和感を持ちました。

![image](https://github.com/ics-creative/160609_animation-image-generator/assets/975273/6a47c171-dfc1-4e25-8d42-fca0aa4622f3)

■課題
「容量最適化」の右側に「？」マークが存在することで、「容量最適化」のチェックボックスと「圧縮方式」が連動しているような印象をもちました。

■前提
- 「容量最適化」のチェックボックスは、一時ファイルのPNGにpngquantを使うかどうかの指定
- 「圧縮方式」の指定は、APNGの圧縮に対する指定
 
■解決案
「？」マークは2箇所に掲載する。 

1. 容量最適化 - 容量最適化とは、ファイルを圧縮し容量を最適化します。気付かない程度に画質を落としています。
2. 圧縮方式 - 圧縮方式により処理時間や容量が代わり……（以下同じ）

※社内Slack（2023年2月6日）より転載

**Comment by ics-nohara** [comment]
@ics-ikeda バージョン5.0でリリースされたため、Closeします。Issue登録ありがとうございました！
